name: qr
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.1.5
  intl: ^0.17.0
  provider: ^6.0.2
  google_fonts: ^2.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.8
  multiavatar: ^0.1.5
  badges: ^2.0.2
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  nb_utils: ^4.4.8
  qr_code_scanner: ^0.6.0
  json_serializable: ^6.0.0
  flutter_svg: ^0.22.0
  get: ^4.6.1
  flutter_vector_icons: ^1.0.0
  file_picker: ^4.0.0
  json_annotation: ^4.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.1.4

flutter:
  assets:
    - images/
    -
  uses-material-design: true

